Rent Mailing
wolox-training/mr-rails pull request #13
Opened 2019-04-11 17:09 UTC by ranuccimariano

# Summary
- Enabled Sidekiq to perform mailing tasks.
- Created the .env file to keep the enviroment variables confidential.

# Screenshot
![screenshot4](https://user-images.githubusercontent.com/48363541/55976643-458e9280-5c63-11e9-8095-a108ffa3640f.jpg)

# Trello Card
https://trello.com/c/sRntnFOg

2019-04-11 19:10 UTC, holywyvern requested changes

2019-04-11 19:10 UTC, holywyvern commented on .env
> +USER_NAME = 'b515166a7f3a5c'
No hagas un commit de tu .env, agregalo en el archivo .gitignore. Y si lo agregaste, pero lo hiciste antes de agregarlo a gitignore vas a tener que hacer otro commit borrando el archivo (una vez hecho ese commit, volve a agregar el .env)

2019-04-11 19:10 UTC, holywyvern commented on config/environments/development.rb
> +    user_name: ENV['USER_NAME'],
Usa Rails secrets (config/secrets.yml) `https://apidock.com/rails/Rails/Application/secrets`

con cosas del estilo de:

```rb
config.action_mailer.smit_settings = {
   user_name: Rails.application.secrets.mailer_user_name,
   # ... seguir usando Rails.application.secrets.propiedad con el resto
}
```

(y en secrets.yml...)

```yml
development:
   mailer_user_name: <%= ENV['USER_NAME'] %>
test:
  mailer_user_name: # ...
production:
   # ...
```

Eso es porque podria ser que en otros entornos (como test) utilices otras variables de entorno, o otro tipo de forma de obtener la configuración.

Además a futuro, se va a transicionar de usar el entorno al nuevo sistema de secrets (https://www.engineyard.com/blog/encrypted-rails-secrets-on-rails-5.1)

2019-04-11 19:10 UTC, holywyvern commented on config/secrets.yml
> +development:
Veo que agregaste el secrets, pero recorda, que tendrias que ser un poco más descriptivo con los nombres y usar esto en lugar de ENV[]

2019-04-12 17:23 UTC, holywyvern approved these changes

2019-04-12 17:32 UTC, ranuccimariano commented on .env
> +USER_NAME = 'b515166a7f3a5c'
Done

2019-04-12 17:32 UTC, ranuccimariano commented on config/environments/development.rb
> +    user_name: ENV['USER_NAME'],
Done

2019-04-12 17:33 UTC, merged