User-DTA item #1
wolox-training/mr-rails pull request #5
Opened 2019-03-21 18:40 UTC by ranuccimariano

Summary
I completed the first item of the card. I still have to test the second item.

Screenshot

Trello Card
https://trello.com/c/5szpWs2i

2019-03-22 11:50 UTC, lucasVoboril reviewed
:smile: :tada: MUY buen PR!!! Te dejo unos comentarios con cosas a tener en cuenta a futuro, pero en general esta genial :heart_eyes: 
El único cambio que haría es: la migración y el modelo de usuario son inconsistentes. Deberían coincidir

2019-03-22 11:50 UTC, lucasVoboril commented on app/controllers/application_controller.rb
> +  include DeviseTokenAuth::Concerns::SetUserByToken
Mira esto: si agregamos en este archivo una nueva linea
```rb
# app/controllers/application_controller.rb
before_action :authenticate_user!
```
Todas las acciones que hagamos dentro de los Controladores van a necesitar un usuario autenticado :wink: sin necesidad de especificarlo.

Nota a futuro: si alguna accion dentro de tu Controlador NO necesita un usuario autenticado hacemos esto:
```rb
# app/controllers/controlador_de_lucas.rb
class ControladorDeLucas < ApiController
  skip_before_action :authenticate_user!, only: %i[sign_up]
  
  def index
    ...
  end
end
```

2019-03-22 11:50 UTC, lucasVoboril commented on config/initializers/devise.rb
> +  config.password_length = 6..128
Es posible que alguna validación para algún proyecto necesitemos cambiar el tamaño minimo o maximo de la contraseña. Si necesitas hacer eso, esta es la linea que tenes que cambiar :smile:

2019-03-22 11:50 UTC, lucasVoboril commented on config/initializers/devise.rb
> +Devise.setup do |config|
:nerd_face: Un comentario general sobre los archivos de configuración: por default tienen muchas lineas comentadas, y una breve descripcion de que es lo que hacen esas lineas comentadas. Si necesitamos cambiar algun comportamiento es probable que necesitemos revisar este archivo

2019-03-22 11:50 UTC, lucasVoboril commented on config/initializers/devise_token_auth.rb
> +  # config.token_lifespan = 2.weeks
Si queres que la sesión de un usuario dure menos tiempo (tenga un token valido por menos tiempo) es posible que quieras cambiar este archivo

2019-03-22 11:50 UTC, lucasVoboril commented on db/migrate/20190321153900_devise_token_auth_create_users.rb
> +      ## Confirmable
:eyes: acá cuidado: fijate que en `app/models/user.rb` el modulo `# :confirmable` lo tenemos comentado: no lo estamos usando. Si querés podes dejarlo comentado en la migración

2019-03-22 13:34 UTC, holywyvern requested changes

2019-03-22 13:34 UTC, holywyvern commented on app/models/user.rb
> +  # :confirmable, :lockable, :timeoutable and :omniauthable
Recordá, cuando no usas código, aunque sea autogenerado, es mejor eliminarlo.

2019-03-22 13:34 UTC, holywyvern commented on db/migrate/20190321153900_devise_token_auth_create_users.rb
> +      ## Confirmable
No, dejar comentado código esta mal, si no lo vamos a usar, directamente se tiene que borrar.

2019-03-22 13:34 UTC, holywyvern commented on db/migrate/20190321153900_devise_token_auth_create_users.rb
> +      ## Confirmable
Es por un tema estadistico, si comentas codigo es probable que nunca lo vayas a usar, nunca pasa que necesitas recuperar código comentado. Y en esos casos, se puede revertir desde el historial de GIT.

Hay casos en los que está bien, como si es codigo de ejemplo, tener comentarios con código, o mientras estas probando algo, pero considerá siempre que en git lo que tiene que estar es "el codigo final" y no "un borrador".

2019-03-22 13:34 UTC, holywyvern commented on db/migrate/20190321153900_devise_token_auth_create_users.rb
> +      # t.string   :unlock_token # Only if unlock strategy is :email or :both
Lo mismo en estos casos, hay que borrar este codigo comentado

2019-03-25 13:12 UTC, holywyvern approved these changes

2019-03-25 13:18 UTC, merged